services:
  backend:
    build: ./web
    container_name: flask_app
    ports:
      - "5001:5000"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-volume
    command: tail -f /dev/null
    volumes:
      - data-volume:/app/data
      - logs-volume:/app/logs
      - ./config:/app/config:ro

networks:
  app-network:
    driver: bridge